### ISSUE TITLE
Implement Geofence rules per WPS process

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#1198]
A new process field is required to possibly limit the rule to a specific WPS process.
The new filed must be exposed both on the UI and the Geofence REST API.

![image](https://user-images.githubusercontent.com/571129/115040702-fcb4e880-9ed1-11eb-9151-988f392717d2.png)

**Comment by simboss** [comment]
@etj I see an immediate need and a more longer term need.

1. we need ASAP the ability to just disallow users to downloa data via WPS; this means we need the ability to manage permissions on single processes
2. it would be good to also be able to impose per user values on the process limits

The plan and estimates should take into account first 1 and then 2.

**Comment by simboss** [comment]
Let's take into account also MapStore GUI work for anything we do.

**Comment by nmco** [comment]
@taba90 we need to come up with a plan (and estimate) for this that we can review with @etj and @giohappy.

**Comment by nmco** [comment]
@fernandor777 is blocked.

**Comment by taba90** [comment]
**Long implementation**
- persistence (DAO), services layers and domain entities for WPS Access Rule are needed on GeoFence project. As per the other kind of rules supported we will have two separate services a READ only one and an ADMIN one that allows write operation on the geofence persistence layer.
- The configurable fields for a WPS rule: priority (required), user, group, instance, address, wpsName, groupName, CatalogMode. (layer and ws do not have meaning here since they are handled by data access rule, moreover as Andrea said above wps process can be chained and thus make difficult to retrieve the layer being requested if any).
Estimate is **2.5** days

- on geoserver geofence-server plugin we need to implement the Wicket components to support rule configuration GeoServer side. We will need a WPS rules table page and a WPS rule configuration page.
- moreover an implementation of the [ProcessAccessManager ](https://github.com/geoserver/geoserver/blob/1631857aae6d1557a93591d995f7d536a89a43d4/src/extension/wps/wps-core/src/main/java/org/geoserver/wps/security/ProcessAccessManager.java#L11) is needed
Estimate is **3.5** days.

- We might consider to have a cache for the WPS rule GeoServer side as exists for DataRule. (**1 day**).


- if also the standalone version needs to support configuration of the rules via UI  a new gwt tab having an editable table of wps rules will need to be added. I don't know that much gwt as a framework so I'm not comfortable in estimating this. However abstraction for the UI component are already there thus seems to be relatively simple to add implementation for the new components. Moreover gwt client and server service will be needed (**3.5 days**).

**Comment by etj** [comment]
My recap (split on the different projects/modules):

| Repo | Module | Task | 
|---|---|---|
|GeoFence| model | Add new class `WPSRule` and related ancillary classes 
|GeoFence| persistence | Add DAOs for new classes 
|GeoFence| services (api+impl) | Add service for CRUD operations <br/> Add service for authorization requests
|GeoFence| rest (api+impl) | *To be decided if we also want a REST interface for such rules.*
|GeoFence| GUI | *I would skip it entirely. <br/>WPS filtering is a new feature completely decoupled from existing ones.*
|GeoServer| geofence-client | Add a `GeoFenceProcessAccessManager`
|GeoServer| geofence-server | Add REST endpoints
|GeoServer| geofence-server | Add GUI for WPSRule admin

Since the WPSRule will be applied on a `ProcessAccessManager` and not a `ResourceAccessManager`, we should add the info for handling  workspace/layer.
Problems in the `ResourceAccessManager`, as reported by @aaime , is that we may be requesting Process1 on LayerA, but Process1 may be chaining Process2, and we won't have any access Rule associating Process2 and LayerA.
Handling WPS auth in a `ProcessAccessManager` we should be able to tell, in any chained step, which process we are executing (by a direct call or chained) and which layers the computation is using.
