### ISSUE TITLE
update POMs for stable branches on geoserver-geonode-ext

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/geonode#1247]
Remember to update the poms in subdirectories as well
- [x] [2.18.6](https://github.com/GeoNode/geoserver-geonode-ext/tree/2.18.6) -> 3.2.x
- [x] [2.19.6](https://github.com/GeoNode/geoserver-geonode-ext/tree/2.19.6) -> 3.3.x 
- [x] [2.20.4](https://github.com/GeoNode/geoserver-geonode-ext/tree/2.20.4) -> 4.x, master
- [x] 2.21.x just prepare repo for future release

**Comment by lpasquali** [comment]
artifacts for 2.18.6 are prepared http://build.geo-solutions.it/jenkins/view/GeoNode/job/GeoNode-GeoServer-EXT-2.18.6/
artifacts for 2.19.6 are prepared http://build.geo-solutions.it/jenkins/view/GeoNode/job/GeoNode-GeoServer-EXT-2.19.6/ 
artifacts for 2.20.4 are prepared (since yesterday) http://build.geo-solutions.it/jenkins/view/GeoNode/job/GeoNode-GeoServer-EXT-2.20.4
