### ISSUE TITLE
[Disasterrisk] Allow to print a report in PDF

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#30]
The generated PDF should also have a template with a cover page, footers and so on which can also be updated.

Take as an example the PDF report generated from here

http://thinkhazard.org/report/293-afghanistan-nimroz/FL

![image](https://cloud.githubusercontent.com/assets/1278021/23896197/c55b5676-08a8-11e7-893e-6965dae059c3.png)

It is ok to enable the PDF download only at Risk Analysis level for now.

**Comment by cezio** [comment]
I'm testing xhtml2pdf, using risks app as a sample, but it seems it doesn't work very well:
 * stable version from pip uses old html5lib api, which is not present and throws error:

```
  File "/home/cezio/.virtualenvs/geonode/bin/xhtml2pdf", line 7, in <module>
    from xhtml2pdf.pisa import command
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/pisa.py", line 3, in <module>
    from xhtml2pdf.document import pisaDocument
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/document.py", line 2, in <module>
    from xhtml2pdf.context import pisaContext
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/context.py", line 23, in <module>
    import xhtml2pdf.parser
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 17, in <module>
    from html5lib import treebuilders, inputstream
ImportError: cannot import name inputstream
```
 * I used master branch from repo, which has this fixed, but parser can't handle more advanced css selectors:
 style from header:

```
      <style type="text/css">[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate){display:none !important;}</style>
```

causes parsing error:

```
cezio@gburek [geonode $]>xhtml2pdf test.html test.pdf 
Converting test.html to /mnt/work/cezio/geosolutions/repos/geonode/test.pdf...
Traceback (most recent call last):
  File "/home/cezio/.virtualenvs/geonode/bin/xhtml2pdf", line 11, in <module>
    load_entry_point('xhtml2pdf==0.2b1', 'console_scripts', 'xhtml2pdf')()
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/pisa.py", line 153, in command
    execute()
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/pisa.py", line 374, in execute
    xml_output=xml_output,
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/document.py", line 97, in pisaDocument
    encoding, context=context, xml_output=xml_output)
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/document.py", line 59, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 702, in pisaParser
    context.parseCSS()
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/context.py", line 522, in parseCSS
    self.css = self.cssParser.parse(self.cssText)
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 443, in parse
    src, stylesheet = self._parseStylesheet(src)
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 547, in _parseStylesheet
    src, ruleset = self._parseRuleset(src)
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 842, in _parseRuleset
    src, selectors = self._parseSelectorGroup(src)
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 853, in _parseSelectorGroup
    src, selector = self._parseSelector(src)
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 867, in _parseSelector
    src, selector = self._parseSimpleSelector(src)
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 921, in _parseSimpleSelector
    src, selector = self._parseSelectorPseudo(src, selector)
  File "/home/cezio/.virtualenvs/geonode/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 996, in _parseSelectorPseudo
    raise self.ParseError('Selector Pseudo Function closing \')\' not found', src, ctxsrc)
xhtml2pdf.w3c.cssParser.CSSParseError: Selector Pseudo Function closing ')' not found:: (u':not(', u'.ng-hide-animate){di')
```

I guess we should try with some streamlined template view. Worst case scenario is manually crafted pdf template to be used directly with reportlab. But then we'll have to handle map view somehow.

**Comment by cezio** [comment]
do we have any dedicated template for printed report? or should we use TH as a sample and make something similar?

**Comment by cezio** [comment]
i've checked TH, they use wkhtmltopdf to generate pdf. It's a standalone binary, luckily it's in repository, although judging from issues and commits, packaged version may be outdated. I'm testing locally pdf generation. it seems we'll need separate view with map for pdf anyway.

**Comment by cezio** [comment]
#39 is related

**Comment by cezio** [comment]
I was trying to get pdf with wkhtmltopdf, both unpatched and patched versions:

unpatched: [test.pdf](https://github.com/geosolutions-it/geonode/files/851226/test.pdf)

patched: 
[test.pdf](https://github.com/geosolutions-it/geonode/files/851227/test.pdf)

Unpatched version uses qt5, while patched version uses custom qt4 (i had to hack build script a bit because there was one type incompatibility in unicode handling). I think we could try a bit more with patched version. While it cant render react app yet, this is known problem (old js engine) and possible fixes exist:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2952

**Comment by afabiani** [comment]
Lets try a proof of concept with a pure client library first.

**Comment by cezio** [comment]
For the record, from the call:
 * client side will generate images for chart and map
 * client side will upload images and legend url to backend
 * backend will generate pdf internally with provided images

things to consider:
 * we'll start with simple html template and cli tool for conversion 
 * if results will be subpar, we should consider assembling pdf with reportlab
 * pdf generation may take some time, so we should be ready to move it to celery (client side should be aware of that too).

**Comment by cezio** [comment]
Preliminary code deployed to first vm. 

* I've added ``pdfReport`` element in risk analysis response: http://disasterrisk-af.geo-solutions.it/risks/data_extraction/loc/AF/ht/EQ/at/impact/an/2/ . It contains url for submitting map, legend and chart images, also GET request will render html version of report (GET view doesn't check if images were uploaded).

```
{..
 "pdfReport": "/risks/data_extraction/loc/AF/ht/EQ/at/impact/an/2/pdf",
...
}
```
* to generate pdf, upload files to that url. Required files/field names:
 ``map``, ``chart``, ``legend``.
* internally this will save uploads to subdirectory in uploads dir (``MEDIA_ROOT`` dir), render html template based on risk analysis id and call html-to-pdf converter, which renders html template to pdf file and saves to subdir with other files.
* there's configuration structure for pdf rendering. Basically, idea is that we could use different backends for rendering. Configuration structure looks like this:

```
RISKS = {'DEFAULT_LOCATION': 'AF',
         'PDF_GENERATOR':
           # name of backend, should be handled with geonode.contrib.risks.pdf_helpers.generate_pdf_NAME.
             {'NAME': 'wkhtmltopdf',
              # path to binary (if needed)
               'BIN': '/usr/bin/wkhtml2pdf',
               # additional static arguments to be used when calling binary
               'ARGS': []}}
```
* besides that, there's ``risk_report`` command, which will generate pdf file to arbitrary location. It's a hakish way to get pdf report without making http requests, so it may not work correcty in some cases. Usage:

> usage: manage.py risk_report [-h] [--version] [-v {0,1,2,3}]
                             [--settings SETTINGS] [--pythonpath PYTHONPATH]
                             [--traceback] [--no-color]
                             risk_id location pdf_output
>
> positional arguments:
  risk_id               ID of risk analysis
  location              Location code
  pdf_output            Result file





* I've installed packaged ``wkhtmltopdf``, which has limited functionality (see previous comments). I have local build of wkhtmltopdf, but it's not entirely static, so there are some unresolved lib dependencies when running it on that vm.
* each ``RiskApp`` has own html template for pdf report (see https://github.com/cezio/geonode/tree/afg_risks_contrib_costbenefit/geonode/contrib/risks/templates/risks/pdf).

**Comment by cezio** [comment]
I've dropped wkhtmltopdf as it was not working properly when installed from package (with unpatched qt), and i couldn't make proper statically linked binary to install it on production instances. I've used weasyprint instead (weasyprint.readthedocs.io/en/latest/). I've changed templates so only report view is rendered (and ``<app>.report.pdf`` is entry point for report's html), because this tool doesn't support multiple inputs.

**Comment by cezio** [comment]
Current implementation:
 * legend upload sometimes fail in client (can't say why exactly), so legend upload is not mandatory
 * uploaded files are stored in ``uploaded`` dir (``MEDIA_ROOT`` if i'm not mistaken), under ``app/<app_name>/loc/<location_code>/ht/<hazard_type>/at/<analysis_type>/an/<analysis_id>/`` path. uploaded files are named with ``<upload_type>_<random>.png`` template (i.e. ``map_dMkI9uv.png``). 
 * for each upload session for a report new ``<random>`` value is generated (7 chars). This is to avoid writing to the same paths by different upload sessions. Random value is later passed to report html view with ``?r=`` query string param. Report html view will use this value to get proper files for map, chart and legend.
 * part of upload session is report generation. internally, weasyprint makes request to webserver to get report html view, generates report and returns path to generated file. 
 * after report is generated, upload view should do cleanup and remove files. To achieve this, we read pdf contents into string, and we remove uploaded files + pdf file before returning response. I tried to use ``Response.close()`` which should be called by WSGI server (per spec), but it wasn't called so files were't removed. Also, ``request_finished`` signal is not suitable, because it doesn't carry request nor response instance.

**Comment by cezio** [comment]
One important note about deployment: there's new pypi package introduced (``WeasyPrint``), which requires libffi (``libffi-dev``) to be installed as well.
