### ISSUE TITLE
[Monitoring] Monitored Resources are empty in Django administration panel

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode#328]
Following requests return empty data even if maps, documents or other valid resource types are available on the server:
```
/monitoring/api/metric_data/request.count/?group_by=resource&last=86400&interval=86400&resource_type=map
```
```
/monitoring/api/metric_data/request.count/?group_by=resource&last=86400&interval=86400&resource_type=document
```
After a first investigation on the Django administration panel, Monitoring Resources are populated only for layer types.
It seems it's needed an 'Alternate' parameter for document resource to enable monitoring https://github.com/geosolutions-it/geonode/blob/master/geonode/documents/views.py#L165-L167.
We were able to add a document in monitoring by add an 'Alternate' text to it but it didn't work for maps.

**Comment by gioscarda** [comment]
For maps, it should be due to the `geonode-mapstore-client` as map viewer: when creating a new map no `register_event` is called inside the `set_geonode_map` of the `django-mapstore-adapter`:

https://github.com/geosolutions-it/django-mapstore-adapter/blob/8069447ceb8f27d90d09173b9d5b92224834eb33/mapstore2_adapter/plugins/serializers.py#L99

so the geonode does not store the map into the `MonitoredResource` table.
@afabiani I would like to discuss it with you.

Documents should work at the `test_analytics` branch.
