### ISSUE TITLE
Layer feature info templates are not used inside maps

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#407]
Reported in https://github.com/mapstand/hub-issues/issues/40

**Comment by simboss** [comment]
I would want to see an analysis and a proposal before doing anything @afabiani .

**Comment by afabiani** [comment]
I would say 2/3 days with the support of a frontend developer. The thing is, MapStore is storing its own templates for layers on map configurations. IMHO the best solution would be to avoid MapStore using its templates at all, completely relying on GeoNode settings instead.

Moreover, it would be good if at a certain point we could extend other properties, like the layer format, default opacity, tiling and caghing options, so that these ones will be also stored somehow on the GeoNode model.

![image](https://user-images.githubusercontent.com/1278021/70702140-e4c1c900-1ccd-11ea-9e97-1adf1ffc68ea.png)

**Comment by afabiani** [comment]
@simboss @giohappy I investigated this issue a bit more and it looks like it is an issue related to GeoNode itself and not MapStore.

In particular the serializer on GeoNode specifically removes the "getFeatureInfo" key from the layer json config.

Fixing it seems to be quite easy.

**Comment by giohappy** [comment]
ok then @afabiani let's fix it. I think it's fine to always force GeoNode to insert the featureInfo template inside the layer config. We don't need to let users edit custom featureinfo templates from MapStore inside GeoNode context.
