### ISSUE TITLE
When a user does not have "Download Permissions" on a vectorial layer, the Feature Grid is Empty

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#618]
This is perceived as a misbehavior, and the user might argue that GeoNode is not working properly.

Moreover, an error message appears on top of the map.

![image.png](https://images.zenhubusercontent.com/5cd44ca368f236637fc7f7f1/74a90042-cd3d-4469-8564-1e072f8790a1)

**Comment by giohappy** [comment]
as discussed with @allyoucanmap we are in favour of keeping this on hold, because we would like to discuss a proper solution for the management of tools activations based on permissions.
This requires some work on MapStore, whic should be prioiritized also in light of the new developments for the GeoNode client.

@allyoucanmap please report here the issue that you're going ot open for the discussion with the MapStore team.

**Comment by allyoucanmap** [comment]
@giohappy here the issue https://github.com/geosolutions-it/MapStore2/issues/6680

**Comment by giohappy** [comment]
@allyoucanmap is `disablePluginIf` available in geonode mapstore client 2.1.x?
