### ISSUE TITLE
Create a report of the current thumbnail generation architecture

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#647]
We want to obtain a clear view of the current implementation:

 - dependencies
 - modules involved, both on the side of GeoNode and Geoserver
 - call paths, both for layers and maps
 - direct relationships with the mapstore client (if any)

A description and possibly a diagram must be attached as comments to this task.

**Comment by simboss** [comment]
@bieganowski, no need to dig the geoserver code, just document how we call it to get the Thumb

**Comment by bieganowski** [comment]
the work on the task is started

**Comment by bieganowski** [comment]
[WIP]

The following is the diagram showing flows of the current implementation of the thumbnails generation.
Tiles with `...` indicate that these parts of the flow were not investigated.

![thumbnails](https://user-images.githubusercontent.com/57660086/106873940-4bc1ee80-66d5-11eb-9793-7303cb6c0df8.png)

(editable version: https://drive.google.com/file/d/1plauidpZ_JkccZabvfq-x6yadVG_-HHY/view?usp=sharing)

There are four major paths for generating the thumbnails - two for maps and two for layers. Starting from the top of the diagram - `geonode_mapstore_client` implements a redux epic, which is triggered in the `geonode_mapstore_client/templates/geonode-mapstore-client/layer_map.html` when handling `DOMContentLoaded` event by "GEONODE:CREATE_MAP_THUMBNAIL" or "GEONODE:CREATE_LAYER_THUMBNAIL" actions. The epic prepares the query's body and the URL (`map` vs `layer`) and POSTs to the Geonode endpoint.

In case of the `layer`, the `geonode.layers.views.layer_thumbnail()` view function is executed, which first checks whether query has a parameter `preview` and whether this parameter equals `react`. If so, the function loads the thumbnail from the body of the request. If not, it tries to render the thumbnail with `_prepare_thumbnail_body_from_opts()`, or directly by `_render_thumbnail()`, if the first method fails. `_prepare_thumbnail_body_from_opts()` function again tries to load the image from the body. In case this operation raises an exception, it executes `_render_thumbnail()` directly with the body parameters. Otherwise, if this operation fails to load the image without an error, the function continues to prepare the input and calls `_render_thumbnail()` with it. Later on, `_render_thumbnail()` calls Geoserver's `/rest/printng/render.png` endpoint.

For the `map` query from `geonode_mapstore_client`, the execution path depends on the `ogc_backend`. If the `ogc_backend` equals `qgis_server`, `geonode.maps.qgis_server_views.set_thumbnail_map` view function is executed, which was not investigated.
On the other hand, if the `ogc_backend` equals `geoserver`, `geonode.maps.views.map_thumbnail` view function is executed, which simply renders thumbnail with `_prepare_thumbnail_body_from_opts()`, or directly by `_render_thumbnail()`, if the first method fails.

**Comment by giohappy** [comment]
@bieganowski this detailed analysis gives quite a clear view of the many situations where something can break :)
Next step is to 

1 - do some stress test of the four principal paths, and try to replicate the failures that occasionally happens (as reported from customers). Often the automatic creation of the thumbnail fails when a map is created or saved, and a manual update creation of the thumbnail is required. Notice that thumbnails can be set either from the Editing tools window or the Metadata Wizard page (do they follow the same path?)

![image](https://user-images.githubusercontent.com/571129/107044263-57401300-67c4-11eb-9827-21834cbc26f3.png)

![image](https://user-images.githubusercontent.com/571129/107044275-5ad39a00-67c4-11eb-969e-6d4c864a89ff.png)

2 - Understand why the thumbanils created after saving a map from the mapstore client looks different from the ones created by the other paths.

**Comment by bieganowski** [comment]
@giohappy 
1) should Geonode be tested only with `ASYNC_SIGNALS` (with celery), or both cases should be considered?
2) is it enough to determine if Mapstore Client and Geonode use the same Geoserver's endpoint, or bodies of the requests are also important?

**Comment by giohappy** [comment]
> 1. should Geonode be tested only with ASYNC_SIGNALS (with celery), or both cases should be considered?

yes, production deployments (should) use the async infrastructure.

> 2. is it enough to determine if Mapstore Client and Geonode use the same Geoserver's endpoint, or bodies of the requests are also important?

both are important I guess, because we obtain different thumbnails so I suspect that different parameteres are requested / calculated.

**Comment by bieganowski** [comment]
[WIP]
LAYERS:
1. loading layer - follows bottom left path of the diagram
    - tries `_prepare_thumbnail_body_from_opts` with `printng`, but it returns `None` instead of an image, so:
    - a fallback is executed fetching thumbnail from `http://localhost:8080/geoserver/ows?service=WMS&version=1.1.0&request=GetMap&layers=geonode:theaters_nyc10&format=image/png&bbox=-74.00933448096204,40.711251428325575,-73.84439803442388,40.8100474377091&crs=EPSG:4326&width=240&height=200&access_token=RT8GIwzSxRGhPhG5FQ8A3BSPwG61pB&styles=theaters_nyc10` with Basic authenticated header
2. Layer -> Editing tools -> Thumbnails -> Set - follows top right path of the diagram

**Comment by giohappy** [comment]
well done @bieganowski. I will close this and an epic will be created for the refactoring of the whole thing.
