### ISSUE TITLE
Implement Basic auth middleware

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#650]
The LOCKDOWN_GEONODE variable [activates the LoginRequiredMiddleware](https://github.com/GeoNode/geonode/blob/20f4161aed99faa1c9c86caf769549c0bd0670e3/geonode/settings.py#L1802), which hijacks the request in case the user is not authenticated. This works fine in case the request is authenticated with the Bearer token, since the [Oauath2TokenMiddleware](https://github.com/GeoNode/geonode/blob/20f4161aed99faa1c9c86caf769549c0bd0670e3/geonode/settings.py#L683) is placed before it, but in case of basic auth the requests can't proceed downstream (where basic auth authentication is done for example inside the proxy or the APIs).

We want to introduce a BasicAuthMiddleware beside the Oauath2TokenMiddleware, which checks the Basic header and authenticates the user in case. We can implement something minimal, because we want it to do the least of work. Basically we should reuse [these lines of code](https://github.com/GeoNode/geonode/blob/24242f3f18b2ab20a6c62abc2326b27d10835849/geonode/base/auth.py#L155-L161) (maybe moving them into a separate method for DRY practice) and use inside  BasicAuthMiddleware.process_request method.

Of course tests must be included.

**Comment by bieganowski** [comment]
Discussion summary:
DRF `SessionAuthentication` only checks `request.user.is_authenticated` property to determine, if a user is authenticated or not, assuming that the `user` was assigned to the `request` by session authentication. (In practice any middleware may assign a user to the request). 
The only way to pass the `LoginRequiredMiddleware`'s check (for a request not to be redirected to the login page), is assigning `request` with `user` property, since `LoginRequiredMiddleware` uses exactly the same approach to filter out unauthorized requests.
The incorrect assumption of correlation between `request.user` and session authentication in DRF, causes that `BasicAuthMiddleware` (created in order to pass the `LoginRequiredMiddleware`'s check for Basic Authenticated requests), will authorize user to access all DRF views, even if they only define `authentication_classes = [SessionAuthentication,]`, regardless of a presence of `BasicAuthentication` in `authentication_classes`.

A similar situation was noticed in `OAuth2TokenMiddleware`, but since DRF does not directly support Oauth, it is assumed that this behavior is wanted (supporting OAuth authentication in DRF without installing and configuring `django-oauth-toolkit`).

To prevent such inconsistency, it was decided, not to introduce another middleware, but rather to extend a check in the `LoginRequiredMiddleware` - if a request has **valid** BasicAuth credentials, let the request pass, even though request.user is not set.

**Comment by giohappy** [comment]
As agree by chat let's go on with this solution.

**Comment by simboss** [comment]
@giohappy is this still open?
