### ISSUE TITLE
Thumbnail not created

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#851]
It looks like we have a regression with thumbnails creation, with two apprently unrelated cases:

 - the thumbnail is not created when a layer is uploaded, and nothing is reported inside the logs
 - setting the thumbnail from the Editing tools raise an issue for a missing style:

```
No such style: ProvCM01012019_g_WGS84
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/thumbs/utils.py", line 217, in get_map
    image = wms.getmap(
  File "/usr/local/lib/python3.8/site-packages/owslib/map/wms111.py", line 269, in getmap
    raise ServiceException(err_message)
owslib.util.ServiceException: No such style: ProvCM01012019_g_WGS84
...Checking if image is a blank image
```

The test was done on master demo (branch 3.2.x) with [this shapefile](https://github.com/geosolutions-it/geonode/files/6694583/ProvCM01012019_g.zip)

**Comment by mattiagiupponi** [comment]
@giohappy 
I just tested the layer creation on `master` and `3.2.x` and is working fine. I'm going to try with `geonode-demo` docker

**Comment by mattiagiupponi** [comment]
After some analysis with @afabiani, we found the issue regarding the Thumbnail creation.
In a nutshell, there was a wrong configuration in GeoServer where it tries to lookup the layer into the master demo instead of the stable demo. @afabiani has already changed the value in GeoServer.

![image](https://user-images.githubusercontent.com/51856725/123089061-c1312000-d426-11eb-8e86-a3581b1a7e28.png)

Now the thumbnail is correctly created. I tried also to set the thumbnail from the Editing tools and works smoothly.

I'm still going to open a PR soo for a minor fix regarding the headers.
