### ISSUE TITLE
Developing django-http-commands

### ISSUE THREAD

**Issue by asgharsir** [geosolutions-it/geonode#920]
Refer Epic #909: 
Issue refers to a proposal:

> "to implement a mechanism inside GeoNode to generate an HTTP API for any management command. The idea is to expose management over a common HTTP endpoint, granting of course full control of which commands we want to be exposed and under which security restrictions."

Although the proposal considered the use of the `BaseCommand` to achieve this, however, the issue also recommended the [harvesting implementation](https://github.com/GeoNode/geonode/blob/master/geonode/harvesting/admin.py) to be taken into account which uses Celery `chord`. Although we don't need the `chord` here, because our HTTP management commands would be from different users and independent of each other, I would favour implementation of Celery instead of that of the BaseCommand for several reasons that I already mentioned in the epic issue.

**So, the brief plan is:**
- Create a model to list management commands that we would like to make available, with specific params.
- Provide secure Admin interfaces to create cron jobs from those commands, with passed arguments.
- Use Celery to handle an async performance of these cron jobs.

**Development Steps:**
1. Update the initial work done in https://github.com/geosolutions-it/django-http-commands in line with the present plan. This means to update the main project app and requirements etc.
2. Create the required models: commands, jobs etc
3. Test the compatibility of our django-http-commands tool with a geonode app.
4. Test the Celery execution of the jobs by adding some data to the models and providing a test endpoint to test our django-http-commands tool.
5. Add a couple of commands' data for any genode management commands.
6. Create Admin interfaces to create cron jobs from those commands.
7. Test these real management commands' execution.
8. BE-FE coordination on dynamic creation of interfaces for any command.
9. QA

**This issue is to cover Development Steps 1 to 4** which aims to demonstrate and test the core design. The time estimate here is specific to this.

After this, there may be separate issues, each with steps 5, 6 and 7 for different management commands we need to test.

**Comment by mattiagiupponi** [comment]
@asgharsir few considerations
- I would to implement all of those feature inside `geonod`e and not as an external app. The idea (as far as i know) is to let `geonode` by as much async as possible, this includes also the commands
- Can you please share some doc about the `cronjobs` in celery (thats is just for my personal knowledge and for some documentation)
- i'd keep separated the admin interface between the actual commands available and the job execution

@afabiani What do you think?

**Comment by afabiani** [comment]
I would change the proposal as follows:

1. Let's extend the GeoNode apis instead of adding and external app as @mattiagiupponi suggested
2. No need for a model to store the commands, we can pass the parameters like django-http-commands already does
3. No need for cron jobs, we need to separate the execution call from the execution itself, that means store the requested parameters somehow and invoke a dispatcher asynchronously later on
4. We need the current admin dashboard action being able to invoke the management commands asynchronously (e.g. batch metadata update and others). Those actions should be able to follow the execution and update the output accordingly

**Comment by asgharsir** [comment]
By external app do you guys mean `django-http-commands` as an installable apps? That's alright if we have the feature built inside `geonode` itself, because I also had a few design questions on that, but I thought we have some reusability in mind.

But if not a model, then what would you suggest a best way of doing this @afabiani : 
> store the requested parameters somehow and invoke a dispatcher asynchronously later on.  

And as to:
> we can pass the parameters like django-http-commands already does.  

It also uses the `ManagementCommand` model and tries to do command parsing and input validation which would not be an issue if we use Celery.  

> We need to separate the execution call from the execution itself.   

This is what exactly Celery does. Why we need to reinvent the async, testable, secure, timeout handling, status-update-featured code of the Celery.

I would suggest the use of Celery instead of the way it is being done in `django-http-command`. What the whole `ManagementCommandView` is still to achieve can be achieved in a couple of lines of more pleasant-to-read code with Celery which is not only already tested, more featured but also readily testable. 

And of course we can invoke a Celery task from anywhere in the project, admin dashboard action inclusive.

**Comment by mattiagiupponi** [comment]
> By external app do you guys mean `django-http-commands` as an installable apps? That's alright if we have the feature built inside `geonode` itself, because I also had a few design questions on that, but I thought we have some reusability in mind.

Yes we mean that this should belong to the core `GeoNode` , is just like another way to handle the current management command that are already in place.

Regarding the model (the `ManagementCommand`) **maybe** as Alessio says is not required.
The actual implementation of `django-http-command` use the model to check if the command is `exposed` but in this case we want to expose all of them. If in some way is possible to pass directly the parameters from the request to the async job, i'm fine to not have the model.

Regarding the last part (no use celery) which is your suggestion @afabiani ? Because i thougth to use celery too. Do you have an example already in place in GeoNode?

**Comment by asgharsir** [comment]
And yes, this might be where I am short of vision. What I understand from resources in the epic, and @mattiagiupponi initial plan, specially the suggested endpoints, we will:
1. secure which commands are allowed and which are not. And we will handle the permissions.
2. users will be able to add jobs, limited to those commands
3. We both had plans to allow params also.

Now when Mattia says "in this case we want to expose all of them", I don't know what are "all of the commands". Where I can find a list of them or be sure that these are the all.

This may give me a needed fact to vision the parameters thing.

**Comment by mattiagiupponi** [comment]
In attach the command list
[commands.txt](https://github.com/geosolutions-it/geonode/files/6929858/commands.txt)

**Comment by asgharsir** [comment]
Thanks @mattiagiupponi for this list.
This discussion with new facts has really changed my complete perception about the epic. Earlier resources gave me impression:
- We are building a `django-tool` not just a `geonode` tool. Where "users" will create jobs from restricted commands with restricted params.
- I was thinking most of the commands would be what our endpoints do or our future endpoint would do. But now I found these command are already written under `BaseCommand`s (so my "rewrite code" arguments get nullfied).

So, I withdraw my whole plan. Let me think again. And sorry @afabiani to bother you with these misperceptions..

**Comment by afabiani** [comment]
@mattiagiupponi yes, we can use Celery, but the Periodic Tasks are not needed IMHO

**Comment by mattiagiupponi** [comment]
> * A POST endpoint to call any command.

Yes, I'll add also a `GET`, `POST`, `PATCH` endpoint (with drf) regarding the model related to the Jobs in running (at least get to get the current status of the job).
It will be useful to have also a `GET` endpoint to retrieve all the commands available (is possible to use a django utils to read them. `from django.core.management import get_commands` will return a list of the available commands (filter for the one with geonode as app`

> * We do not need model for commands

Not for store the commands, but we need one for saving the status of the jobs in running

> * This feature may or may not have its own app. If no separate app, we may have this api in `geonode.views` and I am not sure about celery task. They are very scattered. Perhaps in `geonode.tasks` folder a `management_task.py`. @afabiani your input please?

For me is fine under `geonode.tasks` or place it under `geonode.base` if `tasks` is not a valid choice

> 1. Create the view and Celery .
> 2. Test any first couple of commands.
> 3. Add tests for more commands
> 4. QA

> This issue will be limited to steps 1 and 2, to create the setup and the initial tests.
> @mattiagiupponi please.

Since this is almost a discussion issue, can you please open a new issue with the design of the models (field, etc..) and the estimation? So we can track other discussions about the model in that one.

**Comment by asgharsir** [comment]
Sure. I will open a new issue after we settle with the following:

1. Whether to have Jobs model or not (I would favour this)
2. Where to have `views` and `tasks` module. (If we are going for a model, I suggest to create an app of it to structure from URLs to tests everything in there).

**Comment by mattiagiupponi** [comment]
> 1. Whether to have Jobs model or not (I would favour this)
Agree
> 2. Where to have api and `tasks` module. (If we are going for a model, I suggest to create an app of it to structure from URLs to tests everything in there).
Agree, maybe something like `geonode.commands`

**Comment by giohappy** [comment]
closing in favour of a new project plan
