### ISSUE TITLE
Design the CronJob model, GET endpoint and more test

### ISSUE THREAD

**Issue by asgharsir** [geosolutions-it/geonode#922]
This issue refers to Epic [#909](https://github.com/geosolutions-it/geonode/issues/909), and is the step after the issue [#921](https://github.com/geosolutions-it/geonode/issues/921):

So we need to design the CronJob model, GET endpoint and more test.

**Model**:
- A timestamped model
- Decision on **`status` field whether it should be fixed choices or without fixed choices**.
- Relate to `user` who queued the job.
- `payload` with which job is queued.
- `name` - Also a decision, **what should be the name**. For example: `squashmigrations` or `geonode.base.squashmigrations`? Both may have obvious uses.

`status` field can have "fixed choices" for example based on celery features. This will be only useful if we are going to use these constants.

Second option for `status` is without fixed choices. I am inclined to this one. Because we have diversity of commands and in different commands we may need many different ways of "logging" the status. For example, for a status like: "2 out of 13 steps completed".

**GET endpoint**
Any ideas for the GET endpoint. Should we just return any CronJobs queued by the user. Or should we return all the CronJobs by any user. Or what?

**Comment by mattiagiupponi** [comment]
> `status` field can have "fixed choices" for example based on celery features. This will be only useful if we are going to use these constants.
> Second option for `status` is without fixed choices. I am inclined to this one. Because we have diversity of commands and in different commands we may need many different ways of "logging" the status. For example, for a status like: "2 out of 13 steps completed".

I'll prefer to use fixed status to explain how the job is performing. Because the `status` in my head could be an Enumerator with:
`QUEUED`, `RUNNING`, `SUCCESS`, `FAILED` which represent the status of the job and not log of the running task. In my opinion, what you want to see is almost how the execution is going, so maybe add a `log` field could be enough.

> **GET endpoint**
> Any ideas for the GET endpoint. Should we just return any CronJobs queued by the user. Or should we return all the CronJobs by any user. Or what?

Since only the administrator will have access to this, I'll say to show all the jobs available (paginated), with something like this (as I wrote in my initial proposal)

- /api/v2/command/jobs/
    - will return the list of all jobs available for that command (with reduced information to avoid overloads)
- /api/v2/command/jobs/{id}
    - will return the detailed information of a specific job

I think that is also required to have filters on the GET request. So I want to filter only for the `RUNNING` jobs, I should be able to do something like (here is why having fixed status is helpful):

- /api/v2/command/jobs?status=running
- /api/v2/command/jobs?status=failed

**Comment by giohappy** [comment]
closing in favour of a new project plan
